//action types to change the state of the reducer
const LOADING_STARTED = "LOADING_STARTED";
const LOADING_DONE = "LOADING_DONE";
const REGISTER_SUCCESS = "REGISTER_SUCCESS";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const USER_AUTHENTICATED = "USER_AUTHENTICATED";
const REGISTER_FAIL = "REGISTER_FAIL";
const USER_AUTHENTICATION_FAILED = "USER_AUTHENTICATION_FAILED";
const LOGIN_FAIL = "LOGIN_FAIL";
const LOGOUT_USER = "LOGOUT_USER";
const SET_ALERT = "SET_ALERT";
const REMOVE_ALERT = "REMOVE_ALERT";
const UNIVERSITY_LOADED = "UNIVERSITY_LOADED"
const UNIVERSITY_LOADED_FAILED = "UNIVERSITY_LOADED_FAILED"
const CLEAR_UNIVERSITY = "CLEAR_UNIVERSITY";
const IMG1_RECEIVED = "IMG_RECEIVED";
const IMG2_RECEIVED = "IMG2_RECEIVED";
const IMG3_RECEIVED = "IMG3_RECEIVED";
const IMG_RECEIVED_FAILED = "IMG_RECEIVED_FAILED";
const UNIVERSITY_LOAD_START = "UNIVERSITY_LOAD_START";
const APPLICATION_FORM_SUBMITTED = "APPLICATION_FORM_SUBMITTED";
const APPLICATION_FORM_SAVE_SUCCESS = "APPLICATION_FORM_SAVE_SUCCESS";
const APPLICATION_FORM_SAVE_FAILED = "APPLICATION_FORM_SAVE_FAILED";
const APPLICATION_FORM_RECEIVED = "APPLICATION_FORM_RECEIVED";
const APPLICATION_FORM_RECEIVED_FAILED = "APPLICATION_FORM_RECEIVED_FAILED";
const APPLICATION_LOAD_START = "APPLICATION_LOAD_START";
const APPLICATION_NEW = "APPLICATION_NEW";
const CLEAR_APPLICATION = "CLEAR_APPLICATION";
const WITHDRAW_APPLICATION_SUCCESS = "WITHDRAW_APPLICATION_SUCCESS";

export {
    LOADING_DONE,
    LOADING_STARTED,
    REGISTER_SUCCESS,
    LOGIN_FAIL,
    LOGIN_SUCCESS,
    LOGOUT_USER,
    USER_AUTHENTICATED,
    USER_AUTHENTICATION_FAILED,
    REGISTER_FAIL,
    SET_ALERT,
    REMOVE_ALERT,
    UNIVERSITY_LOADED,
    UNIVERSITY_LOADED_FAILED,
    CLEAR_UNIVERSITY,
    IMG1_RECEIVED,
    IMG2_RECEIVED,
    IMG3_RECEIVED,
    IMG_RECEIVED_FAILED,
    UNIVERSITY_LOAD_START,
    APPLICATION_FORM_SUBMITTED,
    APPLICATION_FORM_SAVE_SUCCESS,
    APPLICATION_FORM_SAVE_FAILED,
    APPLICATION_FORM_RECEIVED,
    APPLICATION_FORM_RECEIVED_FAILED,
    APPLICATION_LOAD_START,
    APPLICATION_NEW,
    CLEAR_APPLICATION,
    WITHDRAW_APPLICATION_SUCCESS,
}